# Header
menu:
  主页: /
  文章: /archives
  随笔: /categories/life
  读书: /douban 
  #相册: /instagram

# SubNav
subnav:
  github: "https://github.com/lpyjsj"
  weibo: "http://weibo.com/u/2394940353/home?wvr=5"
  zhihu: "http://www.zhihu.com/people/xiao-mu-14"
  douban: "http://www.douban.com/people/Peppe/"
  #mail: "lpyjsj@qq.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: "/img/author.jpg"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: peppe

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
# #开启——
# friends:
  # 奥巴马的博客: http://localhost:4000/
  # 卡卡的美丽传说: http://localhost:4000/
  # 本泽马的博客: http://localhost:4000/
  # 吉格斯的博客: http://localhost:4000/
  # 习大大大不同: http://localhost:4000/
  # 托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 学生党一枚